#!/bin/sh
# prefix for package/install directory
PREFIX=${PREFIX:-/usr/local/}

mkdir -p $PREFIX/{share/nfop,bin}

perl -pi'*.bak' -e's,\ \$Bin\ .\ \"/data/\",\"\'$PREFIX'\/share\/nfop\/\",' nfop

install -Dm644 data/gui.glade $PREFIX/share/nfop/gui.glade
install -Dm644 data/icon48.png $PREFIX/share/nfop/icon48.png
install -Dm644 data/icon128.png $PREFIX/share/nfop/icon128.png
install -Dm755 nfop $PREFIX/bin/nfop

mv nfop.bak nfop
